### ISSUE TITLE
BlackWidow Chroma V2: Keyboard not working

### ISSUE THREAD

**Issue by 38leinaD** [moozhub/yum-repo-mooz#2]
Hi,
I installed the driver and polychrimatic from this repo.
The daemon is running and polychromatic succesfully recognizes the keyboard type and lets me set a color/light for the keys. The lights are working fine. But the keys themselfs are not working since this driver is installed.
Before i had the driver installed, regular keys where working but lights were not.
I am using Centos 7 (kernel 3.10.0-862.el7.x86_64).
Any guidance how to get the driver fully working is apreciated.

Thanks

**Comment by moozhub** [comment]
For starters, if you haven't already update your CentOS to 7.5 and try again (sudo yum update)..

If that doesn't work I'd suggest opening a report with the developers of the openrazer driver over at https://github.com/openrazer/openrazer/issues since I don't have the keyboard that you're experiencing the problem with, and there may have been a preexisting issue that was previously opened with them.

The issue page for elmooz is really for RPM / EL7 type problems that you may be having, like the driver isn't loading or polychromatic isn't starting, but it appears both of those are fine if you're able to interface with the driver through the polychromatic tool. Any hardware related problems should be reported to the openrazer developer.

**Comment by moozhub** [comment]
I don't have the hardware to test this issue, but if all that is needed is to run hid-recorder on the usbevent you might be able to try adding a udev rule for the mouse, something like this may suffice, give it a shot and let me know if it works.

Add the below into a new file: `/etc/udev/rules.d/99-razer.rules`

`SUBSYSTEM=="usb", ATTRS{idVendor}=="1532", ATTRS{idProduct}=="0040", RUN+="/usr/bin/hid-recorder"`

The vendor/product values may need to be changed depending on what your dmesg states, I just grabbed those out of the ticket you mentioned. This also assumes you have the hid-replay tool installed.

EDIT: this apparently won't work after looking at the tool because it's default method is user-interactive. You can however tack on the device path to the end of the tool, but seems a bit counter-intuitive because it's purpose is just to record device input.. I'm checking to see if another user with a keyboard is able to correct their problem using the same method, if so and launching hid-recorder fixes their problem I may have to look into this a bit deeper..
